### PR TITLE
[FB] Widgets | Improve clock widget

### PR DESCRIPTION
**Pull request by regularenthropy**
### Checklist
- [x] Referenced all related issues
- [x] Have tested the modifications

---

This PR improves the code of the clock widget

### CODE REVIEW

**Review by surapunoyousei — APPROVED** [review]

**Comment by surapunoyousei** [comment]
Well, This PR breaks Floorp.
image

**Comment by regularenthropy** [comment]
> Well, This PR may break Floorp. image

Strange. In my build it works

**Comment by surapunoyousei** [comment]
Open new Window. after that, It can be see.

**Comment by surapunoyousei** [comment]
I think It's need more delay. The "document.getByElement" is null.

**Comment by regularenthropy** [comment]
Hm. I can suppose that it's the problem occurring if the language is set to Japanese. Everything works fine on my side
image

**Comment by surapunoyousei** [comment]
Well, Current version of Floorp has same problem. need fix (but, this function available after pref)

**Comment by surapunoyousei** [comment]
I'll fix it

**Comment by surapunoyousei** [comment]
> うーん。 言語が日本語に設定されている場合に発生する問題だと推測できます。 私の側ではすべて正常に動作します image

The

> Hm. I can suppose that it's the problem occurring if the language is set to Japanese. Everything works fine on my side image

Show statusbar. I think it is useless

**Comment by regularenthropy** [comment]
> > Hm. I can suppose that it's the problem occurring if the language is set to Japanese. Everything works fine on my side image
> 
> Show statusbar. I think it is useless

image

**Pull request merged**
