### PR TITLE
Fix several grammar mistakes in Floorp's preferences

### PR DESCRIPTION
**Pull request by regularenthropy**
This commit fixes several grammar mistakes in Floorp's preferences and the “contributor” section

### CODE REVIEW

**Review by surapunoyousei — COMMENTED** [review]
This function enables the mica effect by the software called "mica for everyone", so this localization may not be suitable.

Thank you for the pull request!

**Review by surapunoyousei — COMMENTED** [review]
Thank you for proofreading!

**Comment by regularenthropy** [comment]
> 

I got it, thank you. Will be fixed soon.

**Comment by regularenthropy** [comment]
I also think literally no one knows about this software (Mica), so it would be better if there was a link to it somewhere in the preferences.

**Comment by regularenthropy** [comment]
Fixed. By the way, is it possible to join the Floorp team to maintain the Russian translation?

**Comment by surapunoyousei** [comment]
訂正ありがとうございます。

> Fixed. By the way, is it possible to join the Floorp team to maintain the Russian translation?

If you want to, you can become a collaborator on https://github.com/Floorp-Projects/l10n-central/. Japanese source code or English is already localized, so I think it is possible.

**Comment by regularenthropy** [comment]
Great! Thank you.

**Comment by surapunoyousei** [comment]
This request will merge. Add them as collaborators and give them push permissions.
If you don't understand something, raise an issue and mention me and I'll answer in the range you understand about localization.

Thanks for your contribution.

**Pull request merged**
