### PR TITLE
browser-manager.js: unify setters and make sidebar more dynamic

### PR DESCRIPTION
**Pull request by regularenthropy**
This commit reduces setters and makes calculation of the custom-url sidebars more dynamic.

Before merge, please, check if everything is ok

### CODE REVIEW

**Comment by surapunoyousei** [comment]
Thank you. My Linux environment is broken, so I'll try it after building.

**Comment by regularenthropy** [comment]
Do not test for now. I've forgotten to add something.

**Comment by surapunoyousei** [comment]
Got it. I'll be waiting for you

**Comment by regularenthropy** [comment]
> Got it. I'll be waiting for you

Done

**Comment by surapunoyousei** [comment]
Oh, so fast.

**Comment by regularenthropy** [comment]
Yes. I'll create a build in GH Actions for you to test (hopefully it will work)

**Comment by regularenthropy** [comment]
> Yes. I'll create a build in GH Actions for you to test (hopefully it will work)

Linux: https://github.com/regularenthropy/Floorp/actions/runs/3134561660
Debian: https://github.com/regularenthropy/Floorp/actions/runs/3134562634
Windows: https://github.com/regularenthropy/Floorp/actions/runs/3134544596 (Still compiling)

**Comment by surapunoyousei** [comment]
After all, the type of open source that makes it easy to build is convenient in this regard. I'm glad I built it.

It was an aside.

**Comment by surapunoyousei** [comment]
I am verifying now

**Pull request merged**
