### PR TITLE
refactor part 1

### PR DESCRIPTION
**Pull request by regularenthropy**
This PR reduces a lot of static code

### CODE REVIEW

**Comment by surapunoyousei** [comment]
I will test then merge

**Comment by regularenthropy** [comment]
> I will test then merge

Cool. Waiting

**Comment by regularenthropy** [comment]
@surapunoyousei One more question. Why do the sidebar IDs start from 1 and not 0?

**Comment by surapunoyousei** [comment]
Because I would intended to keep the FreaSearch panel  fixed.  I was thinking of having FreaSearch at 0 and starting at 1.

 However, considering the user's choice, we thought that fixing the search engine of the web panel was the same as Bing that Microsoft Edge is doing, so we did not implement it.

**Pull request merged**
