### PR TITLE
browser: bump user agents

### PR DESCRIPTION
**Pull request by regularenthropy**
This PR updates user agents to the latest available.

### CODE REVIEW

**Comment by regularenthropy** [comment]
Now for the test branch

**Comment by surapunoyousei** [comment]
Thank you very much. It's not finished perfectly yet, so I'll move on to finishing tomorrow.

We are also considering following the rapid release.

**Comment by regularenthropy** [comment]
For example, base the code on the main Firefox branch?

**Comment by surapunoyousei** [comment]
> Switch

Yes. It is no exaggeration to say that we changed it to this method to enable fast release tracking.

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Tanzanite

You can update Firefox without much dependence on Firefox by storing patches in this repository and making changes only to the floorp folder.

**Comment by regularenthropy** [comment]
So… It does matter, where the changes made by contributors are committed, right?

**Comment by surapunoyousei** [comment]
> So… It does matter, where the changes made by contributors are committed, right?

Originally, I was looking for a way to switch branches for each version and compress (comparate them into multiple) commits. It has been tested for a while, and the Archive-ESR102 hits it.

I thought there would be no problem if I could switch branches, take over only the code, and see the commit logs from past branches. But, It doesn't change that it's inconvenient.

**Comment by regularenthropy** [comment]
Good decision.

**Pull request closed without merging**
