### PR TITLE
browser-command.js: unify sidebar actions

### PR DESCRIPTION
**Pull request by regularenthropy**
This PR reduces repeatable code related to the sidebar actions

### CODE REVIEW

**Comment by surapunoyousei** [comment]
Thanks.

 We finished integrating the container tabs into the sidebar yesterday, so it looks like we've come full circle with feature updates and bug fixes for the browser manager sidebar.

 I'm a high school student who goes to school six days a week, so it's really helpful.

**Comment by surapunoyousei** [comment]
image

← My personal Twitter account ＆ Official Twitter account 

I can isolate well in the container tab

**Comment by regularenthropy** [comment]
> Thanks.
> 
> We finished integrating the container tabs into the sidebar yesterday, so it looks like we've come full circle with feature updates and bug fixes for the browser manager sidebar.
> 
> I'm a high school student who goes to school six days a week, so it's really helpful.

Hey. The work you've done for Floorp while also studying 6 days per week is truly astonishing, and makes me appreciate it. Actually, I'm more-or-less in the same boat, lol. I'm also developing/localizing Floorp in my spare time, while also studying VFX and two more languages (Polish and German) in university.

About the container sidebar tabs – you did a great job!

**Comment by surapunoyousei** [comment]
Pre3 release is complete, so merge.

https://github.com/Floorp-Projects/Floorp/pull/85#issuecomment-1264333550 Thank you for your kind words!

**Pull request merged**
