### PR TITLE
DEB package: depend on libgdk-pixbuf-2.0-0

### LINKED ISSUE #1535: [Bug]: Floorp DEB package depends on `libgdk-pixbuf2.0-0` instead of `libgdk-pixbuf-2.0-0`
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest supported version of the browser.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [X] I have included relevant screenshots or console outputs.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] This issue is specific to this browser and does not occur in other browsers.

### Bug Summary

The `floorp` package from the [Floorp PPA](https://ppa.floorp.app/) depends on `libgdk-pixbuf2.0-0`, which is marked as a transitional package and in turn depends on `libgdk-pixbuf-2.0-0` As a consequence, Floorp cannot be installed on the Debian testing release, since `libgdk-pixbuf2.0-0` is not available on the Debian testing repository.

You may find the description for `libgdk-pixbuf2.0-0` [here](https://packages.debian.org/sid/libgdk-pixbuf2.0-0). It states that the package is transitional, and that packages that need the library should instead depend on `libgdk-pixbuf-2.0-0`.  
Additionally, you can see that the [Firefox Debian package](https://packages.debian.org/trixie/firefox-esr) depends on `libgdk-pixbuf-2.0-0`.

I've been running Floorp from the tarball release, and I can confirm that Floorp works fine if I install `libgdk-pixbuf-2.0-0`

_NOTE: The difference between the two package names here is that the name of the transitional package, which Floorp currently depends on, is missing a single hyphen:_
```
libgdk-pixbuf-2.0-0
             ^
```

### Reproduction Steps

1. Install Debian Testing (Debian 13 "Trixe" at the time of writing)
2. Add the [Floorp PPA](https://ppa.floorp.app) to your system
3. `apt-get install floorp`

### Expected Behavior

Floorp gets installed normally

### Actual Behavior

APT is unable to resolve dependencies for Floorp

### Screenshots

```
$ sudo apt-get install floorp
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

Unsatisfied dependencies:
 floorp : Depends: libgdk-pixbuf2.0-0 (>= 2.22.0) but it is not installable
Error: Unable to correct problems, you have held broken packages.
```
```
$ apt show libgdk-pixbuf2.0-0
Package: libgdk-pixbuf2.0-0
State: not a real package (virtual)
Notice: Can't select candidate version from package libgdk-pixbuf2.0-0 as it has no candidate
Notice: Can't select versions from package 'libgdk-pixbuf2.0-0' as it is purely virtual
Notice: No packages found
```

### Browser Version

11.21.0

### Operating System

Debian Testing

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by GlowingScrewdriver**
The Floorp DEB package currently depends on `libgdk-pixbuf2.0-0`, which is marked as a transitional package and is unavailable on the Debian Testing repository.

This change makes the package depend on `libgdk-pixbuf-2.0-0` instead.

Fixes #1535 

### Check list
- [x] Referenced all related issues
- [x] Have tested the modifications

### CODE REVIEW

**Comment by surapunoyousei** [comment]
Thanks！

**Comment by GlowingScrewdriver** [comment]
Are you sure you've set up the PPA properly? Run `apt-get update`?

The latest version on the PPA includes this fix, so you shouldn't be facing this issue.
```
$ apt-get show floorp
Package: floorp
Version: 11.22.0
Priority: optional
Section: web
Maintainer: Floorp project
Installed-Size: 305 MB
Provides: gnome-www-browser, www-browser
Depends: libasound2 (>= 1.0.16), libatk1.0-0 (>= 1.12.4), libc6 (>= 2.18), libcairo-gobject2 (>= 1.10.0), libcairo2 (>= 1.10.0), libdbus-1-3 (>= 1.5.12), libfontconfig1 (>= 2.11), libfreetype6 (>= 2.3.5), libgcc1 (>= 1:4.1.1), libgdk-pixbuf-2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.37.0), libgtk-3-0 (>= 3.13.7), libpango-1.0-0 (>= 1.14.0), libpangocairo-1.0-0 (>= 1.14.0), libstdc++6 (>= 4.8), libx11-6, libx11-xcb1, libxcb-shm0, libxcb1, libxcomposite1 (>= 1:0.3-1), libxcursor1 (>> 1.1.2), libxdamage1 (>= 1:1.1), libxext6, libxfixes3, libxi6, libxrandr2 (>= 2:1.4.0), libxrender1, fonts-noto-cjk
Recommends: libavcodec60 | libavcodec-extra60 | libavcodec59 | libavcodec-extra59 | libavcodec58 | libavcodec-extra58 | libavcodec57 | libavcodec-extra57 | libavcodec56 | libavcodec-extra56 | libavcodec55 | libavcodec-extra55 | libavcodec54 | libavcodec-extra54 | libavcodec53 | libavcodec-extra53
Suggests: fonts-stix | otf-stix, fonts-lmodern, libgssapi-krb5-2 | libkrb53, libcanberra0, pulseaudio
Xul-Appid: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
Download-Size: 98.4 MB
APT-Manual-Installed: yes
APT-Sources: https://ppa.floorp.app/amd64 ./ Packages
Description: Floorp is a new Firefox-based,
 privacy-preserving browser developed by the Japanese student community.

Notice: There are 24 additional records. Please use the '-a' switch to see them.
```

**Comment by GlowingScrewdriver** [comment]
Ahh, I see. The Ubuntu 18 repos ship only the old `libgdk-pixbuf2.0-0`, not the new `libgdk-pixbuf-2.0-0`. That's the issue here.
<https://launchpad.net/ubuntu/bionic/+search?text=libgdk-pixbuf2.0-0>

Also, the issue that Librewolf users are facing is the issue that this PR fixed.

**Comment by GlowingScrewdriver** [comment]
@surapunoyousei should we make Floorp depend on

    libgdk-pixbuf-2.0-0 | libgdk-pixbuf2.0-0

instead of just

    libgdk-pixbuf-2.0-0

?

I just noticed that the package description for [`libgdk-pixbuf2.0-0`](https://packages.debian.org/bookworm/libgdk-pixbuf2.0-0) on the Debian repos suggests just this. However, [Firefox from the Debian repos](https://packages.debian.org/sid/firefox) depends only on `libgdk-pixbuf-2.0-0`

**Comment by GlowingScrewdriver** [comment]
Not to my knowledge

**Pull request merged**
